### signup
POST http://localhost:8000/user/signup
content-type: application/json

{
    "name": "tom",
    "email": "tom12@tom.com",
    "password": "secret_code"
}

### signin
POST http://localhost:8000/user/signin
content-type: application/json

{
    "email": "tom12@tom.com",
    "password": "secret_code"
}

### get me
GET http://localhost:8000/user/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZkN2ZlMjMxZmNlMjQ5MTA3MDgzODgiLCJpYXQiOjE2NjgxMjA1NzJ9.l7I230j2k0NZ1liQFC2kKI68Repf-82hHg5QkFKB24o

### create lesson
POST http://localhost:8000/lesson/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZhZGMzM2VlYjJjY2M2MWU1Zjc4ZTQiLCJpYXQiOjE2Njc5NTEwMTV9.CxcDLPWeaRElLM-yMbxG0eub2BzN4py5zcD4Iu6gldU

{
    "title": "tom's title 2",
    "description": "tom1@tom.com is the right email",
    "homework": "41 chapter",
    "link": "google.com"
}

### fetch lessons
GET http://localhost:8000/lesson/lessons
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZhZGMzM2VlYjJjY2M2MWU1Zjc4ZTQiLCJpYXQiOjE2Njc5NTEwMTV9.CxcDLPWeaRElLM-yMbxG0eub2BzN4py5zcD4Iu6gldU
