### signup
POST http://localhost:8000/user/signup
content-type: application/json

{
    "name": "tom",
    "email": "tom12@tom.com",
    "password": "secret_code"
}

### signin
POST http://localhost:8000/user/signin
content-type: application/json

{
    "email": "tom12@tom.com",
    "password": "secret_code"
}

### get me
GET http://localhost:8000/user/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZkN2ZlMjMxZmNlMjQ5MTA3MDgzODgiLCJpYXQiOjE2NjgzMTg3NjV9.ha84RRMXERSTpNdVO7cujB4DMXLGHX0c1d0zvWW4OqQ

### create lesson
POST http://localhost:8000/lesson/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZkN2ZlMjMxZmNlMjQ5MTA3MDgzODgiLCJpYXQiOjE2NjgzMTg3NjV9.ha84RRMXERSTpNdVO7cujB4DMXLGHX0c1d0zvWW4OqQ

{
    "title": "tom's title 2",
    "description": "tom1@tom.com is the right email",
    "homework": "41 chapter",
    "link": "google.com",
    "course": "6365a102dae5113bca0c8fb6"
}

### fetch lessons
GET http://localhost:8000/lesson/lessons
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZkN2ZlMjMxZmNlMjQ5MTA3MDgzODgiLCJpYXQiOjE2NjgzMTg3NjV9.ha84RRMXERSTpNdVO7cujB4DMXLGHX0c1d0zvWW4OqQ



### create course
POST http://localhost:8000/course/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZkN2ZlMjMxZmNlMjQ5MTA3MDgzODgiLCJpYXQiOjE2NjgzMTg3NjV9.ha84RRMXERSTpNdVO7cujB4DMXLGHX0c1d0zvWW4OqQ

{
    "title": "Git",
}

### fetch courses
GET http://localhost:8000/course/courses
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZkN2ZlMjMxZmNlMjQ5MTA3MDgzODgiLCJpYXQiOjE2NjgzMTg3NjV9.ha84RRMXERSTpNdVO7cujB4DMXLGHX0c1d0zvWW4OqQ
