### signup
POST http://localhost:8000/user/signup
content-type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "password": "test"
}

### signin
POST http://localhost:8000/user/signin
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "secret_code"
}

### get me
GET http://localhost:8000/user/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg

### create lesson
POST http://localhost:8000/lesson/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg

{
    "title": "tom's title 2",
    "description": "tom1@tom.com is the right email",
    "homework": "41 chapter",
    "link": "google.com",
    "course": "6365a102dae5113bca0c8fb6"
}

### fetch lessons
GET http://localhost:8000/lesson/lessons
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg



### create course
POST http://localhost:8000/course/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg

{
    "title": "Test",
    "creator": "Test"
}

### fetch courses
GET http://localhost:8000/course/courses
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg


// HOMEWORK
### create hw
POST http://localhost:8000/homework
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg

{
    "text": "Test homework 2",
    "studentId": "6381db447f587110860a4381",
    "lessonId": "63756ec4fdba44a4c2de8f37"
}

### fetch homework
GET http://localhost:8000/homework?id=6381dd0f0cac94d0329dd2f7
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzgxZGI0NDdmNTg3MTEwODYwYTQzODEiLCJpYXQiOjE2Njk0NTQ2NzZ9.npqt7Ip1uE9QZBjZDYIA8IK6G5VcAImqQi2N0y0nZhg







# Telegram Bots
# My chat ID - 794272343

### getme
GET https://api.telegram.org/bot5965431146:AAGXWWL1YH48beGVX28fcL-OXEUFLv_qgfQ/getMe

### getUpdates
GET https://api.telegram.org/bot5965431146:AAGXWWL1YH48beGVX28fcL-OXEUFLv_qgfQ/getUpdates?offset=46272076


### sendMessageToSerg
POST https://api.telegram.org/bot5965431146:AAGXWWL1YH48beGVX28fcL-OXEUFLv_qgfQ/sendMessage
content-type: application/json

{
    "chat_id": "794272343",
    "parse_mode": "MarkdownV2",
    "text": "
        _New homework from NAME_
        [inline URL](http://some.net/lesson?lessonId=638afd80d34ab8e761e2febf&studentId=6381db447f587110860a4381)
        ",
}