name: Deploy main branch to Digitl Ocean droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd /var/www/html/learning-portal/node_server
            git pull origin main
            yarn build
            mv ./buildFrontStatic/* ./public/
            pm2 stop all
            pm2 start "yarn start"
